version: '3'
services:
  cassandra1:
    image: cassandra:latest
    container_name: cassandra1
    networks:
      - lab1
    ports:
      - "9042:9042"

  cassandra2:
    image: cassandra:latest
    container_name: cassandra2
    environment:
      CASSANDRA_SEEDS: "cassandra1"
    networks:
      - lab1
    ports:
      - "9043:9042"

  cassandra3:
    image: cassandra:latest
    container_name: cassandra3
    environment:
      CASSANDRA_SEEDS: "cassandra1"
    networks:
      - lab1
    ports:
      - "9044:9042"
    

networks:
  lab1:
